// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateCategoryDto = {
    name: string;
    /**
     * Auto-generated if empty
     */
    slug?: string;
    /**
     * Parent Category ID
     */
    parentId?: string;
    description?: string;
    imageUrl?: string;
    isActive?: boolean;
};

export type CategoryCountDto = {
    products: number;
    children?: number;
};

export type CategoryDto = {
    id: string;
    name: string;
    slug: string;
    parentId?: string;
    description?: string;
    imageUrl?: string;
    orderIndex: number;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    children?: Array<CategoryDto>;
    _count?: CategoryCountDto;
};

export type SingleCategoryResponseDto = {
    data: CategoryDto;
};

export type PageMetaDto = {
    total: number;
    page: number;
    lastPage: number;
};

export type PaginatedCategoryDataDto = {
    data: Array<CategoryDto>;
    meta: PageMetaDto;
};

export type PaginatedCategoryResponseDto = {
    data: PaginatedCategoryDataDto;
};

export type CategoryTreeResponseDto = {
    data: Array<CategoryDto>;
};

export type UpdateCategoryDto = {
    name?: string;
    /**
     * Auto-generated if empty
     */
    slug?: string;
    /**
     * Parent Category ID
     */
    parentId?: string;
    description?: string;
    imageUrl?: string;
    isActive?: boolean;
    orderIndex?: number;
};

export type CreateBrandDto = {
    name: string;
    slug?: string;
    logoUrl?: string;
    isActive?: boolean;
};

export type UpdateBrandDto = {
    name?: string;
    slug?: string;
    logoUrl?: string;
    isActive?: boolean;
};

export type CreateModelDto = {
    /**
     * Brand ID
     */
    brandId: string;
    /**
     * Model name
     */
    name: string;
    /**
     * Model reference
     */
    reference: string;
    /**
     * Year of model
     */
    year?: number;
    /**
     * Is model active
     */
    isActive?: boolean;
};

export type UpdateModelDto = {
    /**
     * Brand ID
     */
    brandId?: string;
    /**
     * Model name
     */
    name?: string;
    /**
     * Model reference
     */
    reference?: string;
    /**
     * Year of model
     */
    year?: number;
    /**
     * Is model active
     */
    isActive?: boolean;
};

export type DataResponseDto = {
    data: {
        [key: string]: unknown;
    };
};

export type PaginatedResponseDto = {
    data: Array<Array<unknown>>;
    meta: PageMetaDto;
};

export type CreatePriceDto = {
    /**
     * Product variant ID
     */
    variantId: string;
    /**
     * Price type
     */
    priceType: 'BASE' | 'WHOLESALE' | 'PROMO';
    /**
     * Customer type
     */
    customerType: 'B2C' | 'B2B' | 'PARTICULIER' | 'AGENT_COMMERCIAL' | 'REVENDEUR';
    /**
     * Price amount
     */
    amount: number;
    /**
     * Currency code
     */
    currency?: string;
    /**
     * Minimum quantity
     */
    minQuantity?: number;
    /**
     * Valid from date
     */
    validFrom?: string;
    /**
     * Valid to date
     */
    validTo?: string;
    /**
     * Is price active
     */
    isActive?: boolean;
};

export type CreateVariantDto = {
    sku?: string;
    name?: string;
    attributes?: {
        [key: string]: unknown;
    };
    isActive?: boolean;
    prices?: Array<CreatePriceDto>;
    /**
     * Initial stock quantity
     */
    initialStock?: number;
};

export type CreateProductFullDto = {
    name: string;
    slug?: string;
    sku: string;
    description?: string;
    technicalSpecs?: {
        [key: string]: unknown;
    };
    categoryId: string;
    brandId?: string;
    modelId?: string;
    isActive?: boolean;
    requiresInstallation?: boolean;
    isDropshipping?: boolean;
    dropshipSupplierId?: string;
    variants?: Array<CreateVariantDto>;
    /**
     * Array of image URLs
     */
    images?: Array<string>;
};

export type UpdateProductDto = {
    name?: string;
    slug?: string;
    sku?: string;
    description?: string;
    technicalSpecs?: {
        [key: string]: unknown;
    };
    categoryId?: string;
    brandId?: string;
    modelId?: string;
    isActive?: boolean;
    requiresInstallation?: boolean;
    isDropshipping?: boolean;
    dropshipSupplierId?: string;
};

export type UpdateVariantDto = {
    sku?: string;
    name?: string;
    attributes?: {
        [key: string]: unknown;
    };
    isActive?: boolean;
    prices?: Array<CreatePriceDto>;
    /**
     * Initial stock quantity
     */
    initialStock?: number;
};

export type CreatePromotionDto = {
    /**
     * Product variant ID
     */
    variantId: string;
    /**
     * Customer type
     */
    customerType: 'B2C' | 'B2B' | 'PARTICULIER' | 'AGENT_COMMERCIAL' | 'REVENDEUR';
    /**
     * Promotional price
     */
    amount: number;
    /**
     * Valid from date
     */
    validFrom: string;
    /**
     * Valid to date
     */
    validTo: string;
    /**
     * Minimum quantity
     */
    minQuantity?: number;
};

export type UpdatePriceDto = {
    /**
     * Price amount
     */
    amount?: number;
    /**
     * Minimum quantity
     */
    minQuantity?: number;
    /**
     * Valid from date
     */
    validFrom?: string;
    /**
     * Valid to date
     */
    validTo?: string;
    /**
     * Is price active
     */
    isActive?: boolean;
};

export type CreateSupplierDto = {
    name: string;
    contactName?: string;
    email?: string;
    phone?: string;
    address?: string;
    deliveryDelayDays?: number;
    isActive?: boolean;
};

export type UpdateSupplierDto = {
    name?: string;
    contactName?: string;
    email?: string;
    phone?: string;
    address?: string;
    deliveryDelayDays?: number;
    isActive?: boolean;
};

export type ReserveStockDto = {
    /**
     * Quantity to reserve
     */
    quantity: number;
    /**
     * Reference ID (e.g. Order ID)
     */
    referenceId: string;
    /**
     * Reference type
     */
    referenceType: string;
};

export type ReleaseStockDto = {
    /**
     * Quantity to release
     */
    quantity: number;
    /**
     * Reference ID (e.g. Order ID)
     */
    referenceId: string;
    /**
     * Reference type
     */
    referenceType: string;
};

export type StockAdjustmentDto = {
    /**
     * Quantity adjustment (positive or negative)
     */
    quantity: number;
    /**
     * Reason for adjustment
     */
    reason: string;
    /**
     * Supplier ID for restocking
     */
    supplierId?: string;
};

export type CreateCustomerDto = {
    /**
     * Customer ID (from auth provider)
     */
    id: string;
    /**
     * Email address
     */
    email: string;
    /**
     * First name
     */
    firstName?: string;
    /**
     * Last name
     */
    lastName?: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Company name (for B2B)
     */
    companyName?: string;
    /**
     * Tax ID (for B2B)
     */
    taxId?: string;
    /**
     * Customer type
     */
    customerType?: 'PARTICULIER' | 'AGENT_COMMERCIAL' | 'REVENDEUR';
};

export type UpdateCustomerDto = {
    /**
     * First name
     */
    firstName?: string;
    /**
     * Last name
     */
    lastName?: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Company name
     */
    companyName?: string;
    /**
     * Tax ID
     */
    taxId?: string;
    /**
     * Manually upgrade customer type
     */
    customerType?: string;
};

export type CreateOrderDto = {
    /**
     * ID of the cart to convert to order
     */
    cartId: string;
    /**
     * Delivery method
     */
    deliveryMethod: 'PICKUP' | 'HOME_DELIVERY' | 'DROPSHIP';
    /**
     * Shipping address ID (required for delivery)
     */
    shippingAddressId?: string;
    /**
     * Billing address ID
     */
    billingAddressId?: string;
    /**
     * Customer notes
     */
    notes?: string;
};

export type UpdateOrderStatusDto = {
    /**
     * New status
     */
    status: 'DRAFT' | 'PENDING' | 'CONFIRMED' | 'PROCESSING' | 'AWAITING_PAYMENT' | 'PAID' | 'PREPARING' | 'READY_FOR_PICKUP' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | 'REFUNDED';
    /**
     * Notes regarding the update
     */
    notes?: string;
};

export type ScheduleInstallationDto = {
    /**
     * Date and time for installation
     */
    scheduledAt: string;
};

export type CreateQuoteDto = {
    /**
     * Order ID associated with this quote
     */
    orderId?: string;
    /**
     * Cart ID to convert to quote
     */
    cartId?: string;
    /**
     * Installation configuration
     */
    installationConfig?: {
        [key: string]: unknown;
    };
    /**
     * Valid until date
     */
    validUntil?: string;
};

export type AcceptQuoteDto = {
    /**
     * Notes for acceptance
     */
    notes?: string;
};

export type CreatePaymentDto = {
    /**
     * Order ID
     */
    orderId: string;
    /**
     * Payment amount
     */
    amount: number;
    /**
     * Payment method
     */
    method: 'CASH' | 'MOBILE_MONEY' | 'BANK_TRANSFER' | 'CARD' | 'ON_DELIVERY';
    /**
     * Transaction ID from provider
     */
    transactionId?: string;
    /**
     * Proof of payment (reference/file)
     */
    proof?: string;
    /**
     * Additional notes
     */
    notes?: string;
};

export type UpdatePaymentStatusDto = {
    /**
     * New payment status
     */
    status: 'PENDING' | 'PARTIAL' | 'PAID' | 'REFUNDED' | 'FAILED';
    /**
     * Transaction ID (if adding later)
     */
    transactionId?: string;
};

export type AddToCartDto = {
    /**
     * Cart ID if adding to existing cart
     */
    cartId?: string;
    /**
     * Customer ID for authenticated users
     */
    customerId?: string;
    /**
     * Session ID for guest users
     */
    sessionId?: string;
    /**
     * Product variant ID (required if not service)
     */
    variantId?: string;
    /**
     * Service ID (required if not variant)
     */
    serviceId?: string;
    /**
     * Quantity to add
     */
    quantity: number;
};

export type UpdateCartItemDto = {
    /**
     * New quantity
     */
    quantity: number;
};

export type MergeCartDto = {
    /**
     * Guest session ID
     */
    guestSessionId: string;
    /**
     * Customer ID to merge cart into
     */
    customerId: string;
};

export type CreateSystemConfigDto = {
    /**
     * Configuration key
     */
    key: string;
    /**
     * Configuration value
     */
    value: string;
    /**
     * Description of the configuration
     */
    description?: string;
};

export type UpdateSystemConfigDto = {
    /**
     * Configuration value
     */
    value: string;
    /**
     * Description of the configuration
     */
    description?: string;
};

export type FileResponseDto = {
    id: string;
    name: string;
    url: string;
    size: number;
    mimeType: string;
    folderId?: string;
    createdAt: string;
    updatedAt: string;
};

export type CategoriesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Search term
         */
        search?: string;
        order?: 'asc' | 'desc';
        isActive?: boolean;
        /**
         * Filter by parent ID
         */
        parentId?: string;
        /**
         * Include children in response
         */
        includeChildren?: boolean;
    };
    url: '/catalogue/categories';
};

export type CategoriesControllerFindAllResponses = {
    /**
     * Return paginated categories
     */
    200: PaginatedCategoryResponseDto;
};

export type CategoriesControllerFindAllResponse = CategoriesControllerFindAllResponses[keyof CategoriesControllerFindAllResponses];

export type CategoriesControllerCreateData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/catalogue/categories';
};

export type CategoriesControllerCreateResponses = {
    /**
     * Category created
     */
    201: SingleCategoryResponseDto;
};

export type CategoriesControllerCreateResponse = CategoriesControllerCreateResponses[keyof CategoriesControllerCreateResponses];

export type CategoriesControllerGetTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/catalogue/categories/tree';
};

export type CategoriesControllerGetTreeResponses = {
    /**
     * Return category tree
     */
    200: CategoryTreeResponseDto;
};

export type CategoriesControllerGetTreeResponse = CategoriesControllerGetTreeResponses[keyof CategoriesControllerGetTreeResponses];

export type CategoriesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/categories/{id}';
};

export type CategoriesControllerRemoveResponses = {
    /**
     * Category deleted
     */
    200: unknown;
};

export type CategoriesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/categories/{id}';
};

export type CategoriesControllerFindOneResponses = {
    /**
     * Return category details
     */
    200: SingleCategoryResponseDto;
};

export type CategoriesControllerFindOneResponse = CategoriesControllerFindOneResponses[keyof CategoriesControllerFindOneResponses];

export type CategoriesControllerUpdateData = {
    body: UpdateCategoryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/categories/{id}';
};

export type CategoriesControllerUpdateResponses = {
    /**
     * Category updated
     */
    200: SingleCategoryResponseDto;
};

export type CategoriesControllerUpdateResponse = CategoriesControllerUpdateResponses[keyof CategoriesControllerUpdateResponses];

export type BrandsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Search term
         */
        search?: string;
        order?: 'asc' | 'desc';
        isActive?: boolean;
    };
    url: '/catalogue/brands';
};

export type BrandsControllerFindAllResponses = {
    200: unknown;
};

export type BrandsControllerCreateData = {
    body: CreateBrandDto;
    path?: never;
    query?: never;
    url: '/catalogue/brands';
};

export type BrandsControllerCreateResponses = {
    /**
     * Brand created
     */
    201: unknown;
};

export type BrandsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/brands/{id}';
};

export type BrandsControllerRemoveResponses = {
    200: unknown;
};

export type BrandsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/brands/{id}';
};

export type BrandsControllerFindOneResponses = {
    200: unknown;
};

export type BrandsControllerUpdateData = {
    body: UpdateBrandDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/brands/{id}';
};

export type BrandsControllerUpdateResponses = {
    200: unknown;
};

export type ModelControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        brandId?: string;
        includeInactive?: boolean;
    };
    url: '/catalogue/models';
};

export type ModelControllerFindAllResponses = {
    /**
     * Return all models
     */
    200: unknown;
};

export type ModelControllerCreateData = {
    body: CreateModelDto;
    path?: never;
    query?: never;
    url: '/catalogue/models';
};

export type ModelControllerCreateResponses = {
    /**
     * Model created successfully
     */
    201: unknown;
};

export type ModelControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/models/{id}';
};

export type ModelControllerRemoveResponses = {
    /**
     * Model deleted successfully
     */
    200: unknown;
};

export type ModelControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/models/{id}';
};

export type ModelControllerFindOneResponses = {
    /**
     * Return model details
     */
    200: unknown;
};

export type ModelControllerUpdateData = {
    body: UpdateModelDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/models/{id}';
};

export type ModelControllerUpdateResponses = {
    /**
     * Model updated successfully
     */
    200: unknown;
};

export type ProductsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Search term
         */
        search?: string;
        order?: 'asc' | 'desc';
        isActive?: boolean;
        categoryId?: string;
        brandId?: string;
        modelId?: string;
        isDropshipping?: boolean;
        /**
         * Filter by min price
         */
        minPrice?: number;
        /**
         * Filter by max price
         */
        maxPrice?: number;
    };
    url: '/catalogue/products';
};

export type ProductsControllerFindAllResponses = {
    /**
     * Return all products paginated
     */
    200: DataResponseDto & {
        data?: PaginatedResponseDto & {
            data?: Array<CreateProductFullDto>;
        };
    };
};

export type ProductsControllerFindAllResponse = ProductsControllerFindAllResponses[keyof ProductsControllerFindAllResponses];

export type ProductsControllerCreateFullData = {
    body: CreateProductFullDto;
    path?: never;
    query?: never;
    url: '/catalogue/products';
};

export type ProductsControllerCreateFullResponses = {
    /**
     * Product created successfully
     */
    201: unknown;
};

export type ProductsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/products/{id}';
};

export type ProductsControllerRemoveResponses = {
    200: unknown;
};

export type ProductsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/products/{id}';
};

export type ProductsControllerFindOneResponses = {
    200: unknown;
};

export type ProductsControllerUpdateData = {
    body: UpdateProductDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/products/{id}';
};

export type ProductsControllerUpdateResponses = {
    200: unknown;
};

export type ProductsControllerFindBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/catalogue/products/slug/{slug}';
};

export type ProductsControllerFindBySlugResponses = {
    200: unknown;
};

export type ProductsControllerDuplicateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/products/{id}/duplicate';
};

export type ProductsControllerDuplicateResponses = {
    201: unknown;
};

export type VariantsControllerCreateData = {
    body: CreateVariantDto;
    path: {
        productId: string;
    };
    query?: never;
    url: '/catalogue/variants/product/{productId}';
};

export type VariantsControllerCreateResponses = {
    201: unknown;
};

export type VariantsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/variants/{id}';
};

export type VariantsControllerRemoveResponses = {
    200: unknown;
};

export type VariantsControllerUpdateData = {
    body: UpdateVariantDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/variants/{id}';
};

export type VariantsControllerUpdateResponses = {
    200: unknown;
};

export type VariantsControllerUpdateStockData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/variants/{id}/stock';
};

export type VariantsControllerUpdateStockResponses = {
    200: unknown;
};

export type PricesControllerCreateData = {
    body: CreatePriceDto;
    path?: never;
    query?: never;
    url: '/catalogue/prices';
};

export type PricesControllerCreateResponses = {
    /**
     * Price created successfully
     */
    201: unknown;
};

export type PricesControllerFindByVariantData = {
    body?: never;
    path: {
        variantId: string;
    };
    query?: never;
    url: '/catalogue/prices/variant/{variantId}';
};

export type PricesControllerFindByVariantResponses = {
    200: unknown;
};

export type PricesControllerGetEffectivePriceData = {
    body?: never;
    path: {
        variantId: string;
    };
    query: {
        quantity: number;
        customerType: string;
    };
    url: '/catalogue/prices/variant/{variantId}/effective';
};

export type PricesControllerGetEffectivePriceResponses = {
    200: unknown;
};

export type PricesControllerGetBulkPricesData = {
    body?: never;
    path: {
        variantId: string;
    };
    query: {
        customerType: string;
    };
    url: '/catalogue/prices/variant/{variantId}/bulk';
};

export type PricesControllerGetBulkPricesResponses = {
    200: unknown;
};

export type PricesControllerGetPriceHistoryData = {
    body?: never;
    path: {
        variantId: string;
    };
    query?: {
        limit?: number;
    };
    url: '/catalogue/prices/variant/{variantId}/history';
};

export type PricesControllerGetPriceHistoryResponses = {
    200: unknown;
};

export type PricesControllerRemovePromotionData = {
    body?: never;
    path: {
        variantId: string;
    };
    query: {
        customerType: string;
    };
    url: '/catalogue/prices/variant/{variantId}/promotion';
};

export type PricesControllerRemovePromotionResponses = {
    200: unknown;
};

export type PricesControllerApplyPromotionData = {
    body: CreatePromotionDto;
    path: {
        variantId: string;
    };
    query?: never;
    url: '/catalogue/prices/variant/{variantId}/promotion';
};

export type PricesControllerApplyPromotionResponses = {
    201: unknown;
};

export type PricesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/prices/{id}';
};

export type PricesControllerRemoveResponses = {
    200: unknown;
};

export type PricesControllerUpdateData = {
    body: UpdatePriceDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/prices/{id}';
};

export type PricesControllerUpdateResponses = {
    200: unknown;
};

export type SuppliersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Search term
         */
        search?: string;
        order?: 'asc' | 'desc';
        isActive?: boolean;
    };
    url: '/catalogue/suppliers';
};

export type SuppliersControllerFindAllResponses = {
    200: unknown;
};

export type SuppliersControllerCreateData = {
    body: CreateSupplierDto;
    path?: never;
    query?: never;
    url: '/catalogue/suppliers';
};

export type SuppliersControllerCreateResponses = {
    /**
     * Supplier created
     */
    201: unknown;
};

export type SuppliersControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/suppliers/{id}';
};

export type SuppliersControllerRemoveResponses = {
    200: unknown;
};

export type SuppliersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/suppliers/{id}';
};

export type SuppliersControllerFindOneResponses = {
    200: unknown;
};

export type SuppliersControllerUpdateData = {
    body: UpdateSupplierDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/suppliers/{id}';
};

export type SuppliersControllerUpdateResponses = {
    200: unknown;
};

export type SuppliersControllerGetSupplierProductsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/suppliers/{id}/products';
};

export type SuppliersControllerGetSupplierProductsResponses = {
    200: unknown;
};

export type StockControllerGetLowStockItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stock/low-stock';
};

export type StockControllerGetLowStockItemsResponses = {
    /**
     * Return low stock items
     */
    200: unknown;
};

export type StockControllerGetStockData = {
    body?: never;
    path: {
        variantId: string;
    };
    query?: never;
    url: '/stock/{variantId}';
};

export type StockControllerGetStockResponses = {
    /**
     * Return stock level
     */
    200: unknown;
};

export type StockControllerReserveStockData = {
    body: ReserveStockDto;
    path: {
        variantId: string;
    };
    query?: never;
    url: '/stock/{variantId}/reserve';
};

export type StockControllerReserveStockResponses = {
    /**
     * Stock reserved successfully
     */
    201: unknown;
};

export type StockControllerReleaseStockData = {
    body: ReleaseStockDto;
    path: {
        variantId: string;
    };
    query?: never;
    url: '/stock/{variantId}/release';
};

export type StockControllerReleaseStockResponses = {
    /**
     * Stock released successfully
     */
    201: unknown;
};

export type StockControllerAdjustStockData = {
    body: StockAdjustmentDto;
    path: {
        variantId: string;
    };
    query?: never;
    url: '/stock/{variantId}/adjust';
};

export type StockControllerAdjustStockResponses = {
    /**
     * Stock adjusted successfully
     */
    201: unknown;
};

export type StockControllerGetMovementsData = {
    body?: never;
    path: {
        variantId: string;
    };
    query?: {
        limit?: number;
    };
    url: '/stock/{variantId}/movements';
};

export type StockControllerGetMovementsResponses = {
    /**
     * Return movement history
     */
    200: unknown;
};

export type CustomersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/customers';
};

export type CustomersControllerFindAllResponses = {
    200: unknown;
};

export type CustomersControllerCreateData = {
    body: CreateCustomerDto;
    path?: never;
    query?: never;
    url: '/customers';
};

export type CustomersControllerCreateResponses = {
    /**
     * Customer created successfully
     */
    201: unknown;
};

export type CustomersControllerGetTopData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/customers/top';
};

export type CustomersControllerGetTopResponses = {
    200: unknown;
};

export type CustomersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/customers/{id}';
};

export type CustomersControllerFindOneResponses = {
    200: unknown;
};

export type CustomersControllerUpdateData = {
    body: UpdateCustomerDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/customers/{id}';
};

export type CustomersControllerUpdateResponses = {
    /**
     * Customer updated successfully
     */
    200: unknown;
};

export type CustomersControllerGetStatsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/customers/{id}/stats';
};

export type CustomersControllerGetStatsResponses = {
    200: unknown;
};

export type CustomersControllerRefreshStatsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/customers/{id}/refresh-stats';
};

export type CustomersControllerRefreshStatsResponses = {
    201: unknown;
};

export type OrdersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status
         */
        status?: 'DRAFT' | 'PENDING' | 'CONFIRMED' | 'IN_PROGRESS' | 'AWAITING_PAYMENT' | 'PAID' | 'PREPARING' | 'READY_FOR_PICKUP' | 'SHIPPED' | 'DELIVERED' | 'COMPLETED' | 'CANCELLED' | 'REFUNDED';
        /**
         * Filter by order number, customer name, or email
         */
        search?: string;
        /**
         * Filter by customer ID
         */
        customerId?: string;
        /**
         * Filter by delivery method
         */
        deliveryMethod?: 'PICKUP' | 'HOME_DELIVERY' | 'DROPSHIP';
        page?: number;
        limit?: number;
    };
    url: '/orders';
};

export type OrdersControllerFindAllResponses = {
    /**
     * Return all orders paginated
     */
    200: DataResponseDto & {
        data?: PaginatedResponseDto & {
            data?: Array<{
                [key: string]: unknown;
            }>;
        };
    };
};

export type OrdersControllerFindAllResponse = OrdersControllerFindAllResponses[keyof OrdersControllerFindAllResponses];

export type OrdersControllerCreateData = {
    body: CreateOrderDto;
    path?: never;
    query?: never;
    url: '/orders';
};

export type OrdersControllerCreateResponses = {
    /**
     * Order created successfully
     */
    201: unknown;
};

export type OrdersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/{id}';
};

export type OrdersControllerFindOneResponses = {
    /**
     * Return order details
     */
    200: unknown;
};

export type OrdersControllerUpdateStatusData = {
    body: UpdateOrderStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/{id}/status';
};

export type OrdersControllerUpdateStatusResponses = {
    /**
     * Order status updated successfully
     */
    200: unknown;
};

export type OrdersControllerScheduleInstallationData = {
    body: ScheduleInstallationDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/{id}/schedule-installation';
};

export type OrdersControllerScheduleInstallationResponses = {
    /**
     * Installation scheduled successfully
     */
    201: unknown;
};

export type OrdersControllerGenerateWhatsAppData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/{id}/whatsapp';
};

export type OrdersControllerGenerateWhatsAppResponses = {
    201: unknown;
};

export type OrdersControllerGetWhatsAppUrlData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/{id}/whatsapp-url';
};

export type OrdersControllerGetWhatsAppUrlResponses = {
    200: unknown;
};

export type OrdersControllerGenerateStatusUpdateData = {
    body?: never;
    path: {
        id: string;
        status: string;
    };
    query?: never;
    url: '/orders/{id}/whatsapp/status-update';
};

export type OrdersControllerGenerateStatusUpdateResponses = {
    201: unknown;
};

export type OrdersControllerGeneratePaymentReminderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/{id}/whatsapp/payment-reminder';
};

export type OrdersControllerGeneratePaymentReminderResponses = {
    201: unknown;
};

export type QuotesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status
         */
        status?: 'DRAFT' | 'PENDING' | 'SENT' | 'ACCEPTED' | 'REJECTED' | 'EXPIRED';
        /**
         * Filter by quote number or customer
         */
        search?: string;
        /**
         * Filter by order ID
         */
        orderId?: string;
        page?: number;
        limit?: number;
    };
    url: '/quotes';
};

export type QuotesControllerFindAllResponses = {
    /**
     * Return all quotes paginated
     */
    200: DataResponseDto & {
        data?: PaginatedResponseDto & {
            data?: Array<{
                [key: string]: unknown;
            }>;
        };
    };
};

export type QuotesControllerFindAllResponse = QuotesControllerFindAllResponses[keyof QuotesControllerFindAllResponses];

export type QuotesControllerCreateData = {
    body: CreateQuoteDto;
    path?: never;
    query?: never;
    url: '/quotes';
};

export type QuotesControllerCreateResponses = {
    /**
     * Quote created successfully
     */
    201: unknown;
};

export type QuotesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/quotes/{id}';
};

export type QuotesControllerFindOneResponses = {
    /**
     * Return quote details
     */
    200: unknown;
};

export type QuotesControllerAcceptData = {
    body: AcceptQuoteDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/quotes/{id}/accept';
};

export type QuotesControllerAcceptResponses = {
    /**
     * Quote accepted and order created
     */
    201: unknown;
};

export type QuotesControllerRejectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/quotes/{id}/reject';
};

export type QuotesControllerRejectResponses = {
    /**
     * Quote rejected successfully
     */
    200: unknown;
};

export type QuotesControllerGeneratePdfData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/quotes/{id}/pdf';
};

export type QuotesControllerGeneratePdfResponses = {
    201: unknown;
};

export type QuotesControllerCheckExpirationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quotes/check-expirations';
};

export type QuotesControllerCheckExpirationsResponses = {
    201: unknown;
};

export type QuotesControllerGenerateWhatsAppData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/quotes/{id}/whatsapp';
};

export type QuotesControllerGenerateWhatsAppResponses = {
    201: unknown;
};

export type QuotesControllerGetWhatsAppUrlData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/quotes/{id}/whatsapp-url';
};

export type QuotesControllerGetWhatsAppUrlResponses = {
    200: unknown;
};

export type InstallationPricingControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/installation-pricing';
};

export type InstallationPricingControllerFindAllResponses = {
    200: unknown;
};

export type InstallationPricingControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/installation-pricing/{id}';
};

export type InstallationPricingControllerFindOneResponses = {
    200: unknown;
};

export type PaymentControllerFindAllForOrderData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/orders/{orderId}/payments';
};

export type PaymentControllerFindAllForOrderResponses = {
    /**
     * Return all payments for order
     */
    200: unknown;
};

export type PaymentControllerCreateForOrderData = {
    body: CreatePaymentDto;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/orders/{orderId}/payments';
};

export type PaymentControllerCreateForOrderResponses = {
    /**
     * Payment created successfully
     */
    201: unknown;
};

export type PaymentControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payments/{id}';
};

export type PaymentControllerFindOneResponses = {
    /**
     * Return payment details
     */
    200: unknown;
};

export type PaymentControllerUpdateStatusData = {
    body: UpdatePaymentStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/payments/{id}/status';
};

export type PaymentControllerUpdateStatusResponses = {
    /**
     * Payment status updated successfully
     */
    200: unknown;
};

export type PaymentControllerRefundData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payments/{id}/refund';
};

export type PaymentControllerRefundResponses = {
    /**
     * Payment refunded successfully
     */
    200: unknown;
};

export type CartControllerGetOrCreateData = {
    body?: never;
    path?: never;
    query?: {
        customerId?: string;
        sessionId?: string;
    };
    url: '/cart';
};

export type CartControllerGetOrCreateResponses = {
    200: unknown;
};

export type CartControllerGetCartData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        customerType?: string;
    };
    url: '/cart/{id}';
};

export type CartControllerGetCartResponses = {
    200: unknown;
};

export type CartControllerAddItemData = {
    body: AddToCartDto;
    path?: never;
    query?: never;
    url: '/cart/items';
};

export type CartControllerAddItemResponses = {
    /**
     * Item added successfully
     */
    201: unknown;
};

export type CartControllerRemoveItemData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cart/items/{id}';
};

export type CartControllerRemoveItemResponses = {
    /**
     * Item removed successfully
     */
    200: unknown;
};

export type CartControllerUpdateItemData = {
    body: UpdateCartItemDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/cart/items/{id}';
};

export type CartControllerUpdateItemResponses = {
    /**
     * Item updated successfully
     */
    200: unknown;
};

export type CartControllerClearCartData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cart/{id}/clear';
};

export type CartControllerClearCartResponses = {
    /**
     * Cart cleared successfully
     */
    200: unknown;
};

export type CartControllerMergeCartData = {
    body: MergeCartDto;
    path?: never;
    query?: never;
    url: '/cart/merge';
};

export type CartControllerMergeCartResponses = {
    /**
     * Carts merged successfully
     */
    200: unknown;
};

export type SystemConfigControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/config';
};

export type SystemConfigControllerFindAllResponses = {
    /**
     * Return all configurations
     */
    200: unknown;
};

export type SystemConfigControllerCreateData = {
    body: CreateSystemConfigDto;
    path?: never;
    query?: never;
    url: '/admin/config';
};

export type SystemConfigControllerCreateResponses = {
    /**
     * Configuration created
     */
    201: unknown;
};

export type SystemConfigControllerRemoveData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/admin/config/{key}';
};

export type SystemConfigControllerRemoveResponses = {
    /**
     * Configuration deleted successfully
     */
    200: unknown;
};

export type SystemConfigControllerFindOneData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/admin/config/{key}';
};

export type SystemConfigControllerFindOneResponses = {
    /**
     * Return configuration details
     */
    200: unknown;
};

export type SystemConfigControllerUpdateData = {
    body: UpdateSystemConfigDto;
    path: {
        key: string;
    };
    query?: never;
    url: '/admin/config/{key}';
};

export type SystemConfigControllerUpdateResponses = {
    /**
     * Configuration updated successfully
     */
    200: unknown;
};

export type AdminUsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type AdminUsersControllerFindAllResponses = {
    200: unknown;
};

export type AdminUsersControllerCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type AdminUsersControllerCreateResponses = {
    201: unknown;
};

export type AdminUsersControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersControllerRemoveResponses = {
    200: unknown;
};

export type AdminUsersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersControllerFindOneResponses = {
    200: unknown;
};

export type AdminUsersControllerUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersControllerUpdateResponses = {
    200: unknown;
};

export type AdminUsersControllerEmergencySeedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users/emergency-seed';
};

export type AdminUsersControllerEmergencySeedResponses = {
    201: unknown;
};

export type SiteConfigControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/site-config';
};

export type SiteConfigControllerFindAllResponses = {
    200: unknown;
};

export type SiteConfigControllerFindByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/admin/site-config/{key}';
};

export type SiteConfigControllerFindByKeyResponses = {
    200: unknown;
};

export type SiteConfigControllerUpdateData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/admin/site-config/{key}';
};

export type SiteConfigControllerUpdateResponses = {
    200: unknown;
};

export type ActivityLogsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/activity-logs';
};

export type ActivityLogsControllerFindAllResponses = {
    200: unknown;
};

export type ReportsControllerGetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports/dashboard';
};

export type ReportsControllerGetDashboardResponses = {
    200: unknown;
};

export type ReportsControllerGetSalesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date
         */
        startDate?: string;
        /**
         * End date
         */
        endDate?: string;
        /**
         * Grouping period
         */
        period?: 'DAY' | 'WEEK' | 'MONTH' | 'YEAR';
    };
    url: '/reports/sales';
};

export type ReportsControllerGetSalesResponses = {
    200: unknown;
};

export type ReportsControllerGetTopProductsData = {
    body?: never;
    path?: never;
    query: {
        limit: number;
    };
    url: '/reports/top-products';
};

export type ReportsControllerGetTopProductsResponses = {
    200: unknown;
};

export type ReportsControllerGetInventoryValuationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports/inventory-valuation';
};

export type ReportsControllerGetInventoryValuationResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * Return JWT token
     */
    200: unknown;
};

export type DocumentsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents';
};

export type DocumentsControllerFindAllResponses = {
    /**
     * Return all documents
     */
    200: unknown;
};

export type DocumentsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type DocumentsControllerRemoveResponses = {
    /**
     * Document deleted
     */
    200: unknown;
};

export type FilesControllerUploadEntityFileData = {
    body: {
        file?: Blob | File;
    };
    path: {
        /**
         * Entity type (categories, brands, models, products, services)
         */
        entityType: 'categories' | 'brands' | 'models' | 'products' | 'services';
    };
    query?: never;
    url: '/files/upload/{entityType}';
};

export type FilesControllerUploadEntityFileResponses = {
    201: FileResponseDto;
};

export type FilesControllerUploadEntityFileResponse = FilesControllerUploadEntityFileResponses[keyof FilesControllerUploadEntityFileResponses];

export type FilesControllerUploadCategoryImageData = {
    body: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files/upload/categories';
};

export type FilesControllerUploadCategoryImageResponses = {
    201: FileResponseDto;
};

export type FilesControllerUploadCategoryImageResponse = FilesControllerUploadCategoryImageResponses[keyof FilesControllerUploadCategoryImageResponses];

export type FilesControllerUploadBrandLogoData = {
    body: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files/upload/brands';
};

export type FilesControllerUploadBrandLogoResponses = {
    201: FileResponseDto;
};

export type FilesControllerUploadBrandLogoResponse = FilesControllerUploadBrandLogoResponses[keyof FilesControllerUploadBrandLogoResponses];

export type FilesControllerUploadModelImageData = {
    body: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files/upload/models';
};

export type FilesControllerUploadModelImageResponses = {
    201: FileResponseDto;
};

export type FilesControllerUploadModelImageResponse = FilesControllerUploadModelImageResponses[keyof FilesControllerUploadModelImageResponses];

export type FilesControllerUploadProductImageData = {
    body: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files/upload/products';
};

export type FilesControllerUploadProductImageResponses = {
    201: FileResponseDto;
};

export type FilesControllerUploadProductImageResponse = FilesControllerUploadProductImageResponses[keyof FilesControllerUploadProductImageResponses];

export type FilesControllerUploadServiceImageData = {
    body: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files/upload/services';
};

export type FilesControllerUploadServiceImageResponses = {
    201: FileResponseDto;
};

export type FilesControllerUploadServiceImageResponse = FilesControllerUploadServiceImageResponses[keyof FilesControllerUploadServiceImageResponses];

export type FilesControllerDeleteFileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}';
};

export type FilesControllerDeleteFileResponses = {
    200: unknown;
};

export type CreateServiceDto = {
    name: string;
    slug: string;
    description?: string;
    imageUrl?: string;
    isActive?: boolean;
};

export type UpdateServiceDto = {
    name?: string;
    slug?: string;
    description?: string;
    imageUrl?: string;
    isActive?: boolean;
};

export type ServicesControllerCreateData = {
    body: CreateServiceDto;
    path?: never;
    query?: never;
    url: '/catalogue/services';
};

export type ServicesControllerCreateResponses = {
    201: DataResponseDto;
};

export type ServicesControllerCreateResponse = ServicesControllerCreateResponses[keyof ServicesControllerCreateResponses];

export type ServicesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/catalogue/services';
};

export type ServicesControllerFindAllResponses = {
    200: DataResponseDto & {
        data: Array<CreateServiceDto>;
    };
};

export type ServicesControllerFindAllResponse = ServicesControllerFindAllResponses[keyof ServicesControllerFindAllResponses];

export type ServicesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/services/{id}';
};

export type ServicesControllerFindOneResponses = {
    200: DataResponseDto;
};

export type ServicesControllerFindOneResponse = ServicesControllerFindOneResponses[keyof ServicesControllerFindOneResponses];

export type ServicesControllerUpdateData = {
    body: UpdateServiceDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/services/{id}';
};

export type ServicesControllerUpdateResponses = {
    200: DataResponseDto;
};

export type ServicesControllerUpdateResponse = ServicesControllerUpdateResponses[keyof ServicesControllerUpdateResponses];

export type ServicesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/catalogue/services/{id}';
};

export type ServicesControllerRemoveResponses = {
    200: DataResponseDto;
};

export type ServicesControllerRemoveResponse = ServicesControllerRemoveResponses[keyof ServicesControllerRemoveResponses];
